In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\orsc\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\orsc\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\orsc\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\orsc\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\orsc\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\orsc\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install plotly
!pip install sqlalchemy
!pip install scipy
!pip install jupyter

Requirement already satisfied: numpy in c:\users\orsc\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: matplotlib in c:\users\orsc\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\orsc\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in c:\users\orsc\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\orsc\anaconda3\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\orsc\anaconda3\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\orsc\anaconda3\lib\site-packages (from seaborn) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\orsc\anaconda3\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\orsc\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\orsc\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\orsc\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: plotly in c:\users\orsc\anaconda3\lib\site-packages (6.3.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\orsc\anaconda3\lib\site-packages (from plotly) (2.7.0)
Requirement already satisfied: packaging in c:\users\orsc\anaconda3\lib\site-packages (from plotly) (25.0)
Requirement already satisfied: sqlalchemy in c:\users\orsc\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\orsc\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\orsc\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: scipy in c:\users\orsc\anaconda3\lib\site-packages (1.16.3)
Requirement already satisfied: numpy<2.6,>=1.25.2 in c:\users\orsc\anaconda3\lib\site-packages (from scipy) (2.3.5)
Requirement already satisfied: jupyter in c:\users\orsc\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: notebook in c:\users\orsc\anaconda3\lib\site-packages (from jupyter) (7.4.5)
Requirement already satisfied: jupyter-console in c:\users\orsc\anaconda3\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\users\orsc\anaconda3\lib\site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipykernel in c:\users\orsc\anaconda3\lib\site-packages (from jupyter) (6.31.0)
Requirement already satisfied: ipywidgets in c:\users\orsc\anaconda3\lib\site-packages (from jupyter) (8.1.7)
Requirement already satisfied: jupyterlab in c:\users\orsc\anaconda3\lib\site-packages (from jupyter) (4.4.7)
Requirement already satisfied: comm>=0.1.1 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (1.8.16)
Requirement already satisfied: ipython>=7.23.1 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (9.7.0)
Requirement already satisfied: jupyter-client>=8.0.0 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.8.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: packaging>=22 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (25.0)
Requirement already satisfied: psutil>=5.7 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (7.0.0)
Requirement already satisfied: pyzmq>=25 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.2 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (6.5.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\orsc\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: colorama>=0.4.4 in c:\users\orsc\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator>=4.3.2 in c:\users\orsc\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\users\orsc\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in c:\users\orsc\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\orsc\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in c:\users\orsc\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in c:\users\orsc\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\orsc\anaconda3\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\orsc\anaconda3\lib\site-packages (from jedi>=0.18.1->ipython>=7.23.1->ipykernel->jupyter) (0.8.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-client>=8.0.0->ipykernel->jupyter) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.5.0)
Requirement already satisfied: pywin32>=300 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (311)
Requirement already satisfied: six>=1.5 in c:\users\orsc\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.0.0->ipykernel->jupyter) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\orsc\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\orsc\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.0)
Requirement already satisfied: pure_eval in c:\users\orsc\anaconda3\lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\orsc\anaconda3\lib\site-packages (from ipywidgets->jupyter) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\orsc\anaconda3\lib\site-packages (from ipywidgets->jupyter) (3.0.15)
Requirement already satisfied: async-lru>=1.0.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.0.5)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.16.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab->jupyter) (80.9.0)
Requirement already satisfied: anyio in c:\users\orsc\anaconda3\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.10.0)
Requirement already satisfied: certifi in c:\users\orsc\anaconda3\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\users\orsc\anaconda3\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in c:\users\orsc\anaconda3\lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\orsc\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.3.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.3)
Requirement already satisfied: nbformat>=5.3.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: overrides>=5.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.15)
Requirement already satisfied: send2trash>=1.8.2 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jsonschema>=4.18.0 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (4.25.0)
Requirement already satisfied: requests>=2.31 in c:\users\orsc\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.32.5)
Requirement already satisfied: sniffio>=1.1 in c:\users\orsc\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\users\orsc\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\orsc\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.28.0)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.2.1)
Requirement already satisfied: pyyaml>=5.3 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3339-validator in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\orsc\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\orsc\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in c:\users\orsc\anaconda3\lib\site-packages (from nbconvert->jupyter) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in c:\users\orsc\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.3.0)
Requirement already satisfied: defusedxml in c:\users\orsc\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\orsc\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\orsc\anaconda3\lib\site-packages (from nbconvert->jupyter) (3.1.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\orsc\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\orsc\anaconda3\lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\users\orsc\anaconda3\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\users\orsc\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\users\orsc\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\orsc\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\orsc\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.5.0)
Requirement already satisfied: lark>=1.2.2 in c:\users\orsc\anaconda3\lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in c:\users\orsc\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.0)
Requirement already satisfied: pycparser in c:\users\orsc\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.23)
Requirement already satisfied: soupsieve>1.2 in c:\users\orsc\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\orsc\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (4.15.0)
Requirement already satisfied: arrow>=0.15.0 in c:\users\orsc\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.4.0)
Requirement already satisfied: tzdata in c:\users\orsc\anaconda3\lib\site-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2025.2)

In [1]:
import pandas as pd
import numpy as nm
import matplotlib
import seaborn
import plotly
import sqlalchemy
import scipy
import jupyter
print ("packages installed sucessfully")

packages installed sucessfully

In [4]:
fund_master= pd.read_csv("01_fund_master.csv")

In [13]:
print(fund_master.head())

   amfi_code       fund_house                                   scheme_name  \
0     119551  SBI Mutual Fund     SBI Bluechip Fund - Regular Plan - Growth
1     119552  SBI Mutual Fund      SBI Bluechip Fund - Direct Plan - Growth
2     119598  SBI Mutual Fund    SBI Small Cap Fund - Regular Plan - Growth
3     119599  SBI Mutual Fund     SBI Small Cap Fund - Direct Plan - Growth
4     119120  SBI Mutual Fund  SBI Magnum Gilt Fund - Regular Plan - Growth

  category sub_category     plan launch_date                  benchmark  \
0   Equity    Large Cap  Regular  2006-02-14              NIFTY 100 TRI
1   Equity    Large Cap   Direct  2013-01-01              NIFTY 100 TRI
2   Equity    Small Cap  Regular  2009-09-09       BSE 250 SmallCap TRI
3   Equity    Small Cap   Direct  2013-01-01       BSE 250 SmallCap TRI
4     Debt         Gilt  Regular  2000-12-30  CRISIL Dynamic Gilt Index

   expense_ratio_pct  exit_load_pct  min_sip_amount  min_lumpsum_amount  \
0               1.54            1.0             500                1000
1               0.66            1.0             500                1000
2               1.43            1.0             500                1000
3               0.72            1.0             500                1000
4               0.77            0.0             500                1000

    fund_manager risk_category sebi_category_code
0  Sohini Andani      Moderate               EC01
1  Sohini Andani      Moderate               EC01
2  R. Srinivasan     Very High               EC03
3  R. Srinivasan     Very High               EC03
4   Dinesh Ahuja           Low               DC02

In [6]:
fund_master.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [14]:
print(fund_master.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB
None

In [15]:
print(fund_master.shape)

(40, 15)

In [16]:
print("head(),dtype and shape methods checked")

head(),dtype and shape methods checked

In [17]:
nav_history= pd.read_csv("02_nav_history.csv")

In [18]:
nav_history.head(10)

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692
5     119551  2022-01-10  55.2835
6     119551  2022-01-11  56.0878
7     119551  2022-01-12  56.4978
8     119551  2022-01-13  56.2934
9     119551  2022-01-14  56.5926

In [19]:
nav_history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

In [20]:
nav_history.shape

(46000, 3)

In [21]:
print("head(),dtype and shape methods checked for nav_history")

head(),dtype and shape methods checked for nav_history

In [22]:
fund_house= pd.read_csv("03_aum_by_fund_house.csv")

In [23]:
fund_house.head(7)

,date,fund_house,aum_lakh_crore,aum_crore,num_schemes
0,2022-03-31,SBI Mutual Fund,6.05,605000,186
1,2022-03-31,ICICI Prudential MF,4.65,465000,216
2,2022-03-31,HDFC Mutual Fund,4.35,435000,195
3,2022-03-31,Nippon India MF,2.70,270000,177
4,2022-03-31,Kotak Mahindra MF,2.70,270000,168
5,2022-03-31,Aditya Birla Sun Life MF,2.78,278000,199
6,2022-03-31,Axis Mutual Fund,2.50,250000,95

In [24]:
fund_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     object
 1   fund_house      90 non-null     object
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.6+ KB

In [25]:
fund_house.shape

(90, 5)

In [26]:
print("head(),dtype and shape methods checked for fund_house")

head(),dtype and shape methods checked for fund_house

In [27]:
sip_inflows= pd.read_csv("04_monthly_sip_inflows.csv")

In [28]:
sip_inflows.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [29]:
sip_inflows.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     object
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.4+ KB

In [30]:
sip_inflows.shape

(48, 6)

In [31]:
print("head(),dtype and shape methods checked for sip inflows")

head(),dtype and shape methods checked for sip inflows

In [32]:
category_inflows= pd.read_csv("05_category_inflows.csv")

In [33]:
category_inflows.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [34]:
category_inflows.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    object
 1   category          144 non-null    object
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), object(2)
memory usage: 3.5+ KB

In [35]:
category_inflows.shape

(144, 3)

In [36]:
print("head(),dtype and shape methods checked for category inflows")

head(),dtype and shape methods checked for category inflows

In [37]:
industry_folio_cnt= pd.read_csv("06_industry_folio_count.csv")

In [38]:
industry_folio_cnt.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [39]:
industry_folio_cnt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     object
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), object(1)
memory usage: 1.1+ KB

In [40]:
industry_folio_cnt.shape

(21, 6)

In [41]:
print("head(),dtype and shape methods checked for industry folio count")

head(),dtype and shape methods checked for industry folio count

In [42]:
scheme_performance= pd.read_csv("07_scheme_performance.csv")

In [43]:
scheme_performance.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [44]:
scheme_performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [45]:
scheme_performance.shape

(40, 19)

In [46]:
print("head(),dtype and shape methods checked for scheme_performance")

head(),dtype and shape methods checked for scheme_performance

In [47]:
investor_txn= pd.read_csv("08_investor_transactions.csv")

In [48]:
investor_txn.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [49]:
investor_txn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

In [50]:
investor_txn.shape

(32778, 13)

In [51]:
print("head(),dtype and shape methods checked for investor transaction")

head(),dtype and shape methods checked for investor transaction

In [52]:
portfolio_holdings = pd.read_csv("09_portfolio_holdings.csv")

In [53]:
portfolio_holdings.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [54]:
portfolio_holdings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    object
 2   stock_name         322 non-null    object
 3   sector             322 non-null    object
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 20.3+ KB

In [55]:
portfolio_holdings.shape

(322, 8)

In [56]:
print("head(),dtype and shape methods checked for portfolio_holdings")

head(),dtype and shape methods checked for portfolio_holdings

In [57]:
benchmark_indices= pd.read_csv("10_benchmark_indices.csv")

In [58]:
benchmark_indices.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [59]:
benchmark_indices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   object
 1   index_name   8050 non-null   object
 2   close_value  8050 non-null   float64
dtypes: float64(1), object(2)
memory usage: 188.8+ KB

In [60]:
benchmark_indices.shape

(8050, 3)

In [61]:
print("head(),dtype and shape methods checked for benchmark_indices")

head(),dtype and shape methods checked for benchmark_indices